/* Bundles the piece finder for the phone app's hidden web view: finder/entry.ts and the web app's
   web/src/lib/vision, into src/lib/finder-bundle.ts. ONNX Runtime isn't bundled; the page loads it from the CDN.
   Run `npm run build:finder` after changing either, and commit the result. */

import { build } from 'esbuild';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));

// models.ts imports ONNX Runtime; the page has already loaded it as the `ort` global.
const ortGlobal = {
  name: 'ort-global',
  setup(b) {
    b.onResolve({ filter: /^onnxruntime-web(\/wasm)?$/ }, (args) => ({ path: args.path, namespace: 'ort-global' }));
    b.onLoad({ filter: /.*/, namespace: 'ort-global' }, () => ({ contents: 'module.exports = globalThis.ort;', loader: 'js' }));
  },
};

const out = await build({
  entryPoints: [`${root}finder/entry.ts`],
  bundle: true,
  format: 'iife',
  target: 'safari16',
  minify: true,
  write: false,
  legalComments: 'none',
  plugins: [ortGlobal],
  logLevel: 'warning',
});

const js = out.outputFiles[0].text;
writeFileSync(
  `${root}src/lib/finder-bundle.ts`,
  `// Generated by scripts/build-finder.mjs from finder/entry.ts and web/src/lib/vision. Don't edit; run npm run build:finder.\n` +
    `export const FINDER_JS = ${JSON.stringify(js)};\n`,
);
console.log(`src/lib/finder-bundle.ts: ${(js.length / 1024).toFixed(0)} KB`);
